LIST_OF_STATUSES_COPY = (
    ('AVAILABLE', 'Available'),
    ('ONLOAN', 'On Loan'),
    ('PROCESSING', 'Processing'),
)
LIST_OF_STATUSES = (
    ('AVAILABLE', 'Available'),
    ('UNAVAILABLE', 'Unavailable'),
)
LIST_OF_LANGUAGES = (
    ('ARY', 'Arabic'),
    ('BUL', 'Bulgarian'),
    ('CHI', 'Chinese'),
    ('DUT', 'Dutch'),
    ('ENG', 'English'),
    ('FRE', 'French'),
    ('GER', 'German'),
    ('GRE', 'Greek'),
    ('ITA', 'Italian'),
    ('JPN', 'Japanese'),
    ('KOR', 'Korean'),
    ('POR', 'Portuguese'),
    ('RUM', 'Romanian'),
    ('RUS', 'Russian'),
    ('SPA', 'Spanish'),
    ('SWE', 'Swedish'),
    ('TUR', 'Turkish'),
    ('UKR', 'Ukrainian'),
    ('VIE', 'Vietnamese'),
)
# BOOK_CATEGORIES = (  # https://en.wikipedia.org/wiki/List_of_writing_genres
#     ("Action", 'Action'),
#     ("Adventure", 'Adventure'),
#     ("Comic", 'Comic'),
#     ("Crime", 'Crime'),
#     ("Fantasy", 'Fantasy'),
#     ("Fiction", 'Fiction'),
#     ("Historical", 'Historical'),
#     ("Horror", 'Horror'),
#     ("Mystery", 'Mystery'),
#     ("Nautical", 'Nautical'),
#     ("Non-Fiction", 'Non-Fiction'),
#     ("Paranoid", 'Paranoid'),
#     ("Philosophical", 'Philosophical'),
#     ("Psychological", 'Psychological'),
#     ("Romance", 'Romance'),
#     ("Science", 'Science'),
#     ("Speculative", 'Speculative'),
#     ("Superhero", 'Superhero'),
#     ("Western", 'Western'),
# )